### ISSUE TITLE
Node Fee Setup, and how are Node Fees Paid

### ISSUE THREAD

**Issue by cyclone321** [ilsawa/p2pool-ltc#4]
Hello, 
I have setup a node and used  run_p2pool.py --net litecoin -f 1 -a [ltcaddress]  to run my node, however after a few days, I am yet to see any node fees paid to that wallet address, am I doing something wrong ?

sorry if this is not correct place to post.

![image](https://user-images.githubusercontent.com/16553069/33425082-5ac60c34-d5c6-11e7-908c-64b01f71fccd.png)

**Comment by gblass** [comment]
I am having the same problem.  I have my node fee set as .5 and it shows on my web portal.  But I am not getting paid any node rewards?

**Comment by ilsawa** [comment]
Read the code, everything is clear in it https://github.com/ilsawa/p2pool-ltc/blob/master/p2pool/work.py#L197
If there are more questions then it is better to ask them here: https://bitcointalk.org/index.php?topic=18313.0
